from flask import Blueprint, request, jsonify, render_template, session, redirect, url_for
import os
import database

auth_bp = Blueprint('auth', __name__)

# Fetch ADMIN_PASSWORD in blueprint to avoid circular imports
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')

@auth_bp.route('/admin/login', methods=['GET', 'POST'])
def admin_login():
    """Login page for SOC Dashboard. GET = show form, POST = validate password."""
    if request.method == 'GET':
        # Already logged in? Go straight to dashboard.
        if session.get('is_admin'):
            return redirect(url_for('dashboard'))
        return render_template('admin_login.html', error=None)

    # POST — validate password
    password = request.form.get('password', '')
    if password == ADMIN_PASSWORD:
        session['is_admin'] = True
        return redirect(url_for('dashboard'))
    else:
        return render_template('admin_login.html', error='Password salah. Coba lagi.'), 401


@auth_bp.route('/admin/logout')
def admin_logout():
    session.clear()
    return redirect(url_for('auth.admin_login'))


@auth_bp.route('/api/auth/admin', methods=['POST'])
def api_auth_admin():
    """Verify admin password and return user object if valid."""
    data = request.get_json(silent=True)
    if not data or 'password' not in data:
        return jsonify({"error": "Password wajib diisi"}), 400

    if data['password'] == ADMIN_PASSWORD:
        return jsonify({
            "success": True,
            "user": {
                "email": "admin@humanfirewall.local",
                "userName": "SOC Administrator",
                "division": "SOC Team",
                "telegramId": "",
                "role": "admin"
            }
        }), 200
    else:
        return jsonify({"error": "Password salah"}), 401


@auth_bp.route('/api/auth/register-token', methods=['POST'])
def register_token():
    """Register a dashboard token generated by Next.js in the SQLite database."""
    from datetime import datetime, timedelta
    data = request.get_json(silent=True)
    if not data or 'token' not in data or 'email' not in data:
        return jsonify({"error": "token and email are required"}), 400

    email = data['email']
    token = data['token']
    expires_at = data.get('expiresAt')

    if expires_at:
        try:
            expires_dt = datetime.utcfromtimestamp(int(expires_at) / 1000.0).isoformat()
        except Exception:
            expires_dt = (datetime.utcnow() + timedelta(days=30)).isoformat()
    else:
        expires_dt = (datetime.utcnow() + timedelta(days=30)).isoformat()

    conn = database.get_connection()
    try:
        conn.execute('''
            INSERT INTO dashboard_tokens (token, email, expires_at)
            VALUES (?, ?, ?)
        ''', (token, email, expires_dt))
        conn.commit()
        return jsonify({"success": True}), 201
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    finally:
        conn.close()


@auth_bp.route('/api/telegram/user', methods=['GET'])
def get_telegram_user():
    chat_id = request.args.get('chat_id')
    if not chat_id:
        return jsonify({"error": "chat_id is required"}), 400

    conn = database.get_connection()
    try:
        row = conn.execute(
            'SELECT email, divisi, points, daily_streak, badge FROM user_history WHERE telegram_chat_id = ?',
            (str(chat_id),)
        ).fetchone()
        if row:
            # Calculate rank
            rank_row = conn.execute(
                'SELECT count(*) + 1 as rank FROM user_history WHERE points > ?',
                (row["points"],)
            ).fetchone()
            rank = rank_row["rank"] if rank_row else 1
            
            score_val = max(0, min(100, int(row["points"] / 2.0)))
            
            return jsonify({
                "registered": True,
                "email": row["email"],
                "divisi": row["divisi"],
                "points": row["points"],
                "score": score_val,
                "streak": row["daily_streak"] or 0,
                "badge": row["badge"] or "None",
                "rank": rank
            }), 200
        else:
            return jsonify({"registered": False}), 200
    finally:
        conn.close()


@auth_bp.route('/api/auth/validate-token', methods=['GET'])
def validate_token_api():
    token = request.args.get('token')
    if not token:
        return jsonify({"error": "token is required"}), 400

    email = database.validate_dashboard_token(token)
    if not email:
        return jsonify({"valid": False}), 404

    conn = database.get_connection()
    try:
        row = conn.execute('SELECT divisi FROM user_history WHERE email = ?', (email,)).fetchone()
        divisi = row["divisi"] if row else 'Unknown'
    finally:
        conn.close()

    # Derived userName matching Next.js split logic
    import re
    local_part = email.split('@')[0]
    parts = re.split(r'[._]', local_part)
    username = " ".join([p.capitalize() for p in parts])

    return jsonify({
        "valid": True,
        "email": email,
        "userName": username,
        "division": divisi
    }), 200


@auth_bp.route('/api/telegram/command', methods=['POST'])
def telegram_command():
    data = request.get_json(silent=True)
    if not data or 'chat_id' not in data or 'command' not in data:
        return jsonify({"error": "chat_id and command are required"}), 400

    chat_id = str(data['chat_id'])
    cmd = data['command'].strip().lower()
    first_name = data.get('first_name', 'User')

    conn = database.get_connection()
    try:
        # Check if user is registered
        row = conn.execute(
            'SELECT email, divisi, points, daily_streak, badge FROM user_history WHERE telegram_chat_id = ?',
            (chat_id,)
        ).fetchone()

        if not row:
            reply = (
                f"Halo {first_name}! 👋\n\n"
                f"Akun Telegram Anda belum terhubung dengan akun Human Firewall.\n"
                f"Silakan daftarkan email perusahaan Anda melalui bot ini dengan mengetikkan email Anda."
            )
            return jsonify({"reply": reply}), 200

        email = row["email"]
        divisi = row["divisi"]
        points = row["points"]
        streak = row["daily_streak"] or 0
        badge = row["badge"] or "None"

        # Calculate rank
        rank_row = conn.execute(
            'SELECT count(*) + 1 as rank FROM user_history WHERE points > ?',
            (points,)
        ).fetchone()
        rank = rank_row["rank"] if rank_row else 1
        score_val = max(0, min(100, int(points / 2.0)))

        if cmd in ('/start', '/help'):
            reply = (
                f"Halo {first_name}! 👋 Selamat datang kembali di Human Firewall Bot Infranexia.\n\n"
                f"Berikut adalah perintah yang bisa Anda gunakan:\n"
                f"📊 `/profile` atau `/score` — Melihat statistik performa keamanan Anda.\n"
                f"🌐 `/dashboard` — Mendapatkan link akses masuk ke Dashboard personal Anda.\n"
                f"ℹ️ `/help` — Menampilkan pesan bantuan ini.\n\n"
                f"Selain perintah di atas, Anda bisa langsung meneruskan/mengirimkan *URL mencurigakan* atau *file attachment* ke chat ini untuk dianalisis oleh tim keamanan secara otomatis!"
            )
        elif cmd in ('/profile', '/score'):
            reply = (
                f"👤 *Profil Keamanan Anda* 👤\n\n"
                f"📧 Email: `{email}`\n"
                f"🏢 Divisi: {divisi}\n\n"
                f"🏆 *Statistik:* \n"
                f"• Skor Kepatuhan: *{score_val}/100*\n"
                f"• Total Poin: *{points} pts*\n"
                f"• Peringkat Perusahaan: *#{rank}*\n"
                f"• Beruntun Bebas Insiden: *{streak} minggu*\n"
                f"• Lencana Saat Ini: *🛡️ {badge}*\n\n"
                f"Pertahankan kinerja baik Anda untuk melindungi Infranexia! 💪"
            )
        elif cmd == '/dashboard':
            import uuid
            from datetime import datetime, timedelta

            token = str(uuid.uuid4())
            expires_dt = (datetime.utcnow() + timedelta(days=30)).isoformat()

            conn.execute('''
                INSERT INTO dashboard_tokens (token, email, expires_at)
                VALUES (?, ?, ?)
            ''', (token, email, expires_dt))
            conn.commit()

            magic_link = f"http://localhost:3000/auth?token={token}"

            reply = (
                f"🔑 *Link Akses Dashboard Anda* 🔑\n\n"
                f"Silakan klik link di bawah ini untuk masuk ke Dashboard personal Anda secara otomatis:\n\n"
                f"🌐 {magic_link}\n\n"
                f"⚠️ *Penting:* Jangan bagikan link ini kepada siapa pun. Link ini berlaku untuk login otomatis akun Anda."
            )
        else:
            reply = (
                f"Perintah `{data['command']}` tidak dikenali.\n\n"
                f"Ketik `/help` untuk melihat daftar perintah yang tersedia."
            )

        return jsonify({"reply": reply}), 200
    finally:
        conn.close()
