from flask import Blueprint, request, jsonify, render_template, session, redirect, url_for
import os
import database

auth_bp = Blueprint('auth', __name__)

# Fetch ADMIN_PASSWORD in blueprint to avoid circular imports
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')

@auth_bp.route('/admin/login', methods=['GET', 'POST'])
def admin_login():
    """Redirect legacy Flask /admin/login requests directly to Next.js React Login Page."""
    dashboard_base = os.environ.get('NEXT_PUBLIC_BASE_URL', 'http://localhost:3000')
    return redirect(f"{dashboard_base}/admin/login")


@auth_bp.route('/admin/logout')
def admin_logout():
    session.clear()
    return redirect(url_for('auth.admin_login'))


@auth_bp.route('/api/auth/admin', methods=['POST'])
def api_auth_admin():
    """Verify admin password and return user object if valid."""
    data = request.get_json(silent=True)
    if not data or 'password' not in data:
        return jsonify({"error": "Password wajib diisi"}), 400

    if data['password'] == ADMIN_PASSWORD:
        return jsonify({
            "success": True,
            "user": {
                "email": "admin@humanfirewall.local",
                "userName": "SOC Administrator",
                "division": "SOC Team",
                "telegramId": "",
                "role": "admin"
            }
        }), 200
    else:
        return jsonify({"error": "Password salah"}), 401


@auth_bp.route('/api/auth/register-token', methods=['POST'])
def register_token():
    """Register a dashboard token generated by Next.js in the SQLite database."""
    from datetime import datetime, timedelta
    data = request.get_json(silent=True)
    if not data or 'token' not in data or 'email' not in data:
        return jsonify({"error": "token and email are required"}), 400

    email = data['email']
    token = data['token']
    expires_at = data.get('expiresAt')

    if expires_at:
        try:
            expires_dt = datetime.utcfromtimestamp(int(expires_at) / 1000.0).isoformat()
        except Exception:
            expires_dt = (datetime.utcnow() + timedelta(days=30)).isoformat()
    else:
        expires_dt = (datetime.utcnow() + timedelta(days=30)).isoformat()

    conn = database.get_connection()
    try:
        conn.execute('''
            INSERT INTO dashboard_tokens (token, email, expires_at)
            VALUES (?, ?, ?)
        ''', (token, email, expires_dt))
        conn.commit()
        return jsonify({"success": True}), 201
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    finally:
        conn.close()


@auth_bp.route('/api/telegram/user', methods=['GET'])
def get_telegram_user():
    chat_id = request.args.get('chat_id')
    if not chat_id:
        return jsonify({"error": "chat_id is required"}), 400

    conn = database.get_connection()
    try:
        row = conn.execute(
            'SELECT email, divisi, points, daily_streak, badge FROM user_history WHERE telegram_chat_id = ?',
            (str(chat_id),)
        ).fetchone()
        if row:
            # Calculate rank
            rank_row = conn.execute(
                'SELECT count(*) + 1 as rank FROM user_history WHERE points > ?',
                (row["points"],)
            ).fetchone()
            rank = rank_row["rank"] if rank_row else 1
            
            score_val = max(0, min(100, int(row["points"] / 2.0)))
            
            return jsonify({
                "registered": True,
                "email": row["email"],
                "divisi": row["divisi"],
                "points": row["points"],
                "score": score_val,
                "streak": row["daily_streak"] or 0,
                "badge": row["badge"] or "None",
                "rank": rank
            }), 200
        else:
            return jsonify({"registered": False}), 200
    finally:
        conn.close()


@auth_bp.route('/api/auth/validate-token', methods=['GET'])
def validate_token_api():
    token = request.args.get('token')
    if not token:
        return jsonify({"error": "token is required"}), 400

    email = database.validate_dashboard_token(token)
    if not email:
        return jsonify({"valid": False}), 404

    conn = database.get_connection()
    try:
        row = conn.execute('SELECT divisi FROM user_history WHERE email = ?', (email,)).fetchone()
        divisi = row["divisi"] if row else 'Unknown'
    finally:
        conn.close()

    # Derived userName matching Next.js split logic
    import re
    local_part = email.split('@')[0]
    parts = re.split(r'[._]', local_part)
    username = " ".join([p.capitalize() for p in parts])

    return jsonify({
        "valid": True,
        "email": email,
        "userName": username,
        "division": divisi
    }), 200


@auth_bp.route('/api/telegram/command', methods=['POST'])
def telegram_command():
    data = request.get_json(silent=True)
    if not data or 'chat_id' not in data or 'command' not in data:
        return jsonify({"error": "chat_id and command are required"}), 400

    chat_id = str(data['chat_id'])
    cmd = data['command'].strip()
    cmd_lower = cmd.lower()
    first_name = data.get('first_name', 'User')

    conn = database.get_connection()
    try:
        dashboard_base = os.environ.get('NEXT_PUBLIC_BASE_URL', 'http://localhost:3000')

        # ── 1. Handle Email Input (e.g. name@domain.com or name@infranexia.co.id) ──
        if '@' in cmd or cmd_lower.endswith('.local') or cmd_lower.endswith('.com') or cmd_lower.endswith('.id'):
            input_email = cmd.strip()
            import random
            otp_code = str(random.randint(100000, 999999))

            user_row = conn.execute('SELECT email FROM user_history WHERE email = ?', (input_email,)).fetchone()
            if not user_row:
                divisi = database.derive_divisi_from_email(input_email) if hasattr(database, 'derive_divisi_from_email') else 'General'
                database.add_employee(input_email, divisi)

            database.create_otp(input_email, chat_id, otp_code)

            subject = "Human Firewall — Kode Verifikasi OTP Telegram"
            body = (
                f"Halo Karyawan,<br><br>"
                f"Kode OTP verifikasi Telegram Anda adalah: <b>{otp_code}</b><br><br>"
                f"Ketikkan kode 6 digit ini di chat bot Telegram untuk menyelesaikan verifikasi.<br>"
                f"Salam,<br><b>Tim IT Security</b>"
            )
            database.create_inbox_email(input_email, subject, body)

            reply = (
                f"📧 Email <b>{input_email}</b> diterima.

"
                f"Kode OTP verifikasi telah dikirimkan ke <b>Inbox Webmail</b> Anda.

"
                f"Silakan ketikkan <b>6 digit kode OTP</b> tersebut di sini untuk menghubungkan akun Telegram Anda!"
            )
            return jsonify({"reply": reply}), 200

        # ── 2. Handle 6-Digit OTP Verification Input ──
        if cmd.isdigit() and len(cmd) == 6:
            otp_row = conn.execute(
                'SELECT email, otp_code FROM telegram_otp WHERE telegram_chat_id = ? AND is_verified = 0 ORDER BY created_at DESC LIMIT 1',
                (chat_id,)
            ).fetchone()

            if otp_row and otp_row["otp_code"] == cmd:
                target_email = otp_row["email"]
                database.update_user_telegram_chat_id(target_email, chat_id)
                conn.execute('UPDATE telegram_otp SET is_verified = 1 WHERE telegram_chat_id = ?', (chat_id,))
                conn.commit()
                reply = (
                    f"✅ <b>Verifikasi Berhasil!</b>

"
                    f"Akun Telegram Anda resmi terhubung dengan email <code>{target_email}</code>.

"
                    f"📌 <b>Perintah yang Bisa Anda Gunakan:</b>
"
                    f"• <code>/profile</code> — Lihat statistik performa & skor kepatuhan Anda.
"
                    f"• <code>/dashboard</code> — Dapatkan link login otomatis ke Dashboard personal Anda.
"
                    f"• <code>/help</code> — Lihat panduan bantuan kapan saja."
                )
            else:
                reply = "❌ Kode OTP salah atau telah kedaluwarsa. Silakan ketik ulang email perusahaan Anda untuk meminta OTP baru."
            return jsonify({"reply": reply}), 200

        # ── 3. Check User Registration Status ──
        row = conn.execute(
            'SELECT email, divisi, points, daily_streak, badge FROM user_history WHERE telegram_chat_id = ?',
            (chat_id,)
        ).fetchone()

        if cmd_lower in ('/start', '/help', 'start', 'help') or not row:
            if not row:
                reply = (
                    f"Halo {first_name}! 👋 Selamat datang di <b>Afferent Security Bot</b>.

"
                    f"Akun Telegram Anda belum terhubung dengan akun perusahaan.

"
                    f"📧 <b>Panduan Pendaftaran Akun (3 Langkah):</b>
"
                    f"1. Ketikkan <b>email perusahaan Anda</b> (contoh: <code>nama@infranexia.co.id</code>) di chat ini.
"
                    f"2. Buka Webmail Anda untuk melihat <b>6 digit kode OTP</b>.
"
                    f"3. Ketikkan 6 digit kode OTP tersebut di sini.

"
                    f"💡 <b>Laporan Ancaman Langsung:</b>
"
                    f"Anda juga bisa langsung meneruskan <b>URL mencurigakan</b> atau <b>File attachment</b> ke chat ini kapan saja untuk dianalisis otomatis oleh VirusTotal & AI!"
                )
            else:
                reply = (
                    f"Halo {first_name}! 👋 Selamat datang di <b>Afferent Security Bot</b>.

"
                    f"📌 <b>Daftar Perintah Resmi:</b>
"
                    f"• <code>/profile</code> — Lihat statistik performa & skor kepatuhan Anda.
"
                    f"• <code>/dashboard</code> — Dapatkan link login otomatis ke Dashboard personal Anda.
"
                    f"• <code>/help</code> — Menampilkan pesan panduan ini.

"
                    f"💡 <b>Cara Melaporkan Ancaman:</b>
"
                    f"• Kirimkan <b>URL mencurigakan</b> (berisi <code>http://...</code>)
"
                    f"• Kirimkan <b>Lampiran File</b> (PDF, EXE, DOCX, TXT)"
                )
            return jsonify({"reply": reply}), 200

        email = row["email"]
        divisi = row["divisi"]
        points = row["points"]
        streak = row["daily_streak"] or 0
        badge = row["badge"] or "None"

        rank_row = conn.execute(
            'SELECT count(*) + 1 as rank FROM user_history WHERE points > ?',
            (points,)
        ).fetchone()
        rank = rank_row["rank"] if rank_row else 1
        score_val = max(0, min(100, int(points / 2.0)))

        if cmd_lower in ('/profile', '/score', 'profile', 'score'):
            reply = (
                f"👤 <b>Profil Keamanan Anda</b> 👤

"
                f"📧 Email: <code>{email}</code>
"
                f"🏢 Divisi: {divisi}

"
                f"🏆 <b>Statistik Performa:</b>
"
                f"• Skor Kepatuhan: <b>{score_val}/100</b>
"
                f"• Total Poin: <b>{points} pts</b>
"
                f"• Peringkat Perusahaan: <b>#{rank}</b>
"
                f"• Beruntun Bebas Insiden: <b>{streak} minggu</b>
"
                f"• Lencana Saat Ini: <b>🛡️ {badge}</b>

"
                f"Pertahankan kinerja baik Anda untuk melindungi perusahaan! 💪"
            )
        elif cmd_lower in ('/dashboard', 'dashboard'):
            import uuid
            from datetime import datetime, timedelta

            token = str(uuid.uuid4())
            expires_dt = (datetime.utcnow() + timedelta(days=30)).isoformat()

            conn.execute('''
                INSERT INTO dashboard_tokens (token, email, expires_at)
                VALUES (?, ?, ?)
            ''', (token, email, expires_dt))
            conn.commit()

            magic_link = f"{dashboard_base}/auth?token={token}"

            reply = (
                f"🔑 <b>Link Akses Dashboard Anda</b> 🔑

"
                f"Silakan klik link di bawah ini untuk masuk ke Dashboard personal Anda secara otomatis:

"
                f"🌐 {magic_link}

"
                f"⚠️ <b>Penting:</b> Jangan bagikan link ini kepada siapa pun."
            )
        else:
            reply = (
                f"Perintah <code>{cmd}</code> tidak dikenali.

"
                f"Ketik <code>/help</code> untuk melihat daftar perintah yang tersedia."
            )

        return jsonify({"reply": reply}), 200
    finally:
        conn.close()
