from flask import Blueprint, request, jsonify, render_template, session, redirect, url_for
import os
import database

auth_bp = Blueprint('auth', __name__)

# Fetch ADMIN_PASSWORD in blueprint to avoid circular imports
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')

@auth_bp.route('/admin/login', methods=['GET', 'POST'])
def admin_login():
    """Login page for SOC Dashboard. GET = show form, POST = validate password."""
    if request.method == 'GET':
        # Already logged in? Go straight to dashboard.
        if session.get('is_admin'):
            return redirect(url_for('dashboard'))
        return render_template('admin_login.html', error=None)

    # POST — validate password
    password = request.form.get('password', '')
    if password == ADMIN_PASSWORD:
        session['is_admin'] = True
        return redirect(url_for('dashboard'))
    else:
        return render_template('admin_login.html', error='Password salah. Coba lagi.'), 401


@auth_bp.route('/admin/logout')
def admin_logout():
    session.clear()
    return redirect(url_for('auth.admin_login'))


@auth_bp.route('/api/auth/admin', methods=['POST'])
def api_auth_admin():
    """Verify admin password and return user object if valid."""
    data = request.get_json(silent=True)
    if not data or 'password' not in data:
        return jsonify({"error": "Password wajib diisi"}), 400

    if data['password'] == ADMIN_PASSWORD:
        return jsonify({
            "success": True,
            "user": {
                "email": "admin@humanfirewall.local",
                "userName": "SOC Administrator",
                "division": "SOC Team",
                "telegramId": "",
                "role": "admin"
            }
        }), 200
    else:
        return jsonify({"error": "Password salah"}), 401


@auth_bp.route('/api/auth/register-token', methods=['POST'])
def register_token():
    """Register a dashboard token generated by Next.js in the SQLite database."""
    from datetime import datetime, timedelta
    data = request.get_json(silent=True)
    if not data or 'token' not in data or 'email' not in data:
        return jsonify({"error": "token and email are required"}), 400

    email = data['email']
    token = data['token']
    expires_at = data.get('expiresAt')

    if expires_at:
        try:
            expires_dt = datetime.utcfromtimestamp(int(expires_at) / 1000.0).isoformat()
        except Exception:
            expires_dt = (datetime.utcnow() + timedelta(days=30)).isoformat()
    else:
        expires_dt = (datetime.utcnow() + timedelta(days=30)).isoformat()

    conn = database.get_connection()
    try:
        conn.execute('''
            INSERT INTO dashboard_tokens (token, email, expires_at)
            VALUES (?, ?, ?)
        ''', (token, email, expires_dt))
        conn.commit()
        return jsonify({"success": True}), 201
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    finally:
        conn.close()


@auth_bp.route('/api/telegram/user', methods=['GET'])
def get_telegram_user():
    chat_id = request.args.get('chat_id')
    if not chat_id:
        return jsonify({"error": "chat_id is required"}), 400

    conn = database.get_connection()
    try:
        row = conn.execute(
            'SELECT email, divisi FROM user_history WHERE telegram_chat_id = ?',
            (str(chat_id),)
        ).fetchone()
        if row:
            return jsonify({
                "registered": True,
                "email": row["email"],
                "divisi": row["divisi"]
            }), 200
        else:
            return jsonify({"registered": False}), 200
    finally:
        conn.close()
